
DROP TABLE IF EXISTS rating CASCADE;
DROP TABLE IF EXISTS vote CASCADE;
DROP TABLE IF EXISTS alternative CASCADE;
DROP TABLE IF EXISTS ballot CASCADE;
DROP TABLE IF EXISTS criterion CASCADE;
DROP TABLE IF EXISTS decision CASCADE;
DROP TABLE IF EXISTS person CASCADE;
